---

- name: tasks for VNC
  hosts: all
  become: true

  tasks:
  - name: Install a list of packages 
    yum:
      name:
        - "@Server with GUI"
        - tigervnc-server 
        - mesa-libGL
        - gconf-editor 
      state: present
    
  - name: Create Folder for VNC
    ansible.builtin.file:
      path: /home/opc/.vnc/
      owner: opc
      group: opc
      mode: 0755
      state: directory

  - name: Create file for Password
    ansible.builtin.file:
      path: /home/opc/.vnc/passwd
      owner: opc
      group: opc
      mode: '0600'
      state: touch

  - name: Create password
    shell: |
      echo Oracle! | vncpasswd -f > /home/opc/.vnc/passwd

  - name: Set up resolution 
    ansible.builtin.command:
      cmd: vncserver -nolisten local -geometry 1680x1050


