---
# tasks file for openfoam

- name: Install a list of packages 
  yum:
    name:
      - libGLU
    state: present

- name: Create /nfs/cluster/OpenFOAM/install
  become: true
  file:
    path: "{{cluster_nfs_path}}/OpenFOAM/install"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes
    
- name: wget download openfoam
  get_url:
    url: "https://objectstorage.us-ashburn-1.oraclecloud.com/p/3EgVwQENXyVrafbKoHNnQIJprt3jTT25iOVjs5vb9uUSGu_rUQb5DXjfqmTfwF2i/n/hpc/b/bucket-20201112-1340/o/openfoam7_OL77_RDMA.tar"
    dest: "{{cluster_nfs_path}}/OpenFOAM/install/openfoam7_OL77_RDMA.tar"
      
      
- name: untar Openfoam step 
  unarchive:
    src: "{{cluster_nfs_path}}/OpenFOAM/install/openfoam7_OL77_RDMA.tar"
    dest: "{{cluster_nfs_path}}/OpenFOAM/install" 
    
- name: Create /nfs/cluster/OpenFOAM/work
  become: true
  file:
    path: "{{cluster_nfs_path}}/OpenFOAM/work"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes
    
- name: wget download motobike
  get_url:
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/JnZ4PqxqrYVqoX5_3ErNJcHU6--KlkPUXUEamJSo3R8/n/hpc/b/HPC_BENCHMARKS/o/motorbike_RDMA.tgz"
    dest: "{{cluster_nfs_path}}/OpenFOAM/work/motorbike_RDMA.tgz"
      
      
- name: untar motobike step 
  unarchive:
    src: "{{cluster_nfs_path}}/OpenFOAM/work/motorbike_RDMA.tgz"
    dest: "{{cluster_nfs_path}}/OpenFOAM/work"     
    
    
- name: Create /nfs/cluster/paraview
  become: true
  file:
    path: "{{cluster_nfs_path}}/paraview"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes
    
- name: wget download paraview
  shell: 'curl -d submit="Download" -d version="v4.4" -d type="binary" -d os="Linux" -d downloadFile="ParaView-4.4.0-Qt4-Linux-64bit.tar.gz" https://www.paraview.org/paraview-downloads/download.php > {{cluster_nfs_path}}/paraview/paraview.tar.gz'
      
- name: untar paraview step 
  unarchive:
    src: "{{cluster_nfs_path}}/paraview/paraview.tar.gz"
    dest: "{{cluster_nfs_path}}/paraview"         
    
    
- name: create tcp hostfile
  template:
    src: templates/hostfile_tcp.j2
    dest: "{{cluster_nfs_path}}/OpenFOAM/work/hostfile"
    
    
    

    

